- name: variables from files
  hosts: web
  vars:
  - vars.yaml
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{COURSE}}, Duration is: {{DURATION}}, Trainer : {{TRAINER}}"