- name: variables to print
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  - name: DURATION
    prompt: please enter the duration
    private: false
  - name: TRAINER
    prompt: please enter the trainer name
    private: false    
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, i'm learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"